title:             Blog
email:             facee22av@naver.com
description:       HEECHANG KWON
author:            HEECHANG
baseurl:
url:               "http://heechang7832.github.io"

# Social Profiles
twitter_username:  SBootstrap
github_username:   BlackrockDigital
facebook_username: StartBootstrap

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
