title:             Blog
email:             facee22av@naver.com
description:       HEECHANG KWON
author:            HEECHANG KWON
baseurl:
url:               "http://heechang7832.github.io"

# Social Profiles
twitter_username:
github_username:   HEECHANG7832
facebook_username:

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
